FROM alpine

ARG ARTHAS_VERSION="3.0.5"
ARG MIRROR=false

ENV MAVEN_HOST=https://repo1.maven.org/maven2 \
  ALPINE_HOST=dl-cdn.alpinelinux.org \
  MIRROR_MAVEN_HOST=http://maven.aliyun.com/repository/public \
  MIRROR_ALPINE_HOST=mirrors.aliyun.com 

# if use mirror change to aliyun mirror site
RUN if $MIRROR; then MAVEN_HOST=${MIRROR_MAVEN_HOST} ;ALPINE_HOST=${MIRROR_ALPINE_HOST} ; sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_HOST}/g" /etc/apk/repositories ; fi && \
  # download & install arthas
  wget -qO /tmp/arthas.zip "${MAVEN_HOST}/com/taobao/arthas/arthas-packaging/${ARTHAS_VERSION}/arthas-packaging-${ARTHAS_VERSION}-bin.zip" && \
  mkdir -p /opt/arthas && \
  unzip /tmp/arthas.zip -d /opt/arthas && \
  rm /tmp/arthas.zip
