FROM maven:3.8.4-openjdk-8 as mavenrepo

RUN mvn -pl web-ui,tunnel-server package -DskipTests

FROM openjdk:8-jdk-alpine
ENV TZ=Asia/Shanghai
ENV JAVA_OPTS="-Xmx256m -Xms256m -Xmn128m"

COPY --from=mavenrepo /tunnel-server/target/arthas-tunnel-server-3.6.7-fatjar.jar /usr/local/app.jar

EXPOSE 8080

CMD ["java", "-jar", "${JAVA_OPTS}", "/usr/local/app.jar"]