logging:
  file:
    name: ${spring.application.name}

server:
  port: 9999

arthas:
  server:
    port: 7777
  tunnel:
    users:
      - name: arthas
        password: 123456
        roles: '*'
      - name: user
        password: 123456
        roles:
          - eden-gateway
          - eden-demo-cola
      - name: manager
        password: 123456
        roles:
          - eden-demo-cola