/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arthas_VmTool */

#ifndef _Included_arthas_VmTool
#define _Included_arthas_VmTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arthas_VmTool
 * Method:    check
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arthas_VmTool_check0
  (JNIEnv *, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    getInstances
 * Signature: (Ljava/lang/Class;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_arthas_VmTool_getInstances
  (JNIEnv *, jclass, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    sumInstanceSize
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_arthas_VmTool_sumInstanceSize
  (JNIEnv *, jclass, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    getInstanceSize
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_arthas_VmTool_getInstanceSize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     arthas_VmTool
 * Method:    countInstances
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_arthas_VmTool_countInstances
  (JNIEnv *, jclass, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    getAllLoadedClasses
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_arthas_VmTool_getAllLoadedClasses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
