/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arthas_VmTool */

#ifndef _Included_arthas_VmTool
#define _Included_arthas_VmTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arthas_VmTool
 * Method:    check0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_arthas_VmTool_check0
  (JNIEnv *, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    getInstances0
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_arthas_VmTool_getInstances0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    sumInstanceSize0
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_arthas_VmTool_sumInstanceSize0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    getInstanceSize0
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_arthas_VmTool_getInstanceSize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     arthas_VmTool
 * Method:    countInstances0
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_arthas_VmTool_countInstances0
  (JNIEnv *, jclass, jclass);

/*
 * Class:     arthas_VmTool
 * Method:    getAllLoadedClasses0
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_arthas_VmTool_getAllLoadedClasses0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
