/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vdian_vclub_MemoryAnalyzer */

#ifndef _Included_com_vdian_vclub_MemoryAnalyzer
#define _Included_com_vdian_vclub_MemoryAnalyzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vdian_vclub_MemoryAnalyzer
 * Method:    getInstances
 * Signature: (Ljava/lang/Class;)Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_com_vdian_vclub_MemoryAnalyzer_getInstances
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_vdian_vclub_MemoryAnalyzer
 * Method:    sumInstanceSize
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_com_vdian_vclub_MemoryAnalyzer_sumInstanceSize
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_vdian_vclub_MemoryAnalyzer
 * Method:    getInstanceSize
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_vdian_vclub_MemoryAnalyzer_getInstanceSize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_vdian_vclub_MemoryAnalyzer
 * Method:    countInstances
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_com_vdian_vclub_MemoryAnalyzer_countInstances
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_vdian_vclub_MemoryAnalyzer
 * Method:    getAllLoadedClasses
 * Signature: ()Ljava/util/LinkedList;
 */
JNIEXPORT jobject JNICALL Java_com_vdian_vclub_MemoryAnalyzer_getAllLoadedClasses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
